components:
  headers:
    x-tidepool-session-token:
      description: A Tidepool session token
      schema:
        pattern: ^[a-zA-Z0-9\-_]+?\.[a-zA-Z0-9\-_]+?\.([a-zA-Z0-9\-_]+)?$
        title: Tidepool Session Token
        type: string
  parameters:
    deviceAuthorizationId:
      in: path
      name: deviceAuthorizationId
      required: true
      schema:
        description: BSON ObjectId
        maxLength: 24
        minLength: 24
        pattern: ^[a-f0-9]{24}
        title: Device Authorization Id
        type: string
    userId:
      in: path
      name: userId
      required: true
      schema:
        $ref: '#/components/schemas/userId'
  schemas:
    Quantile:
      additionalProperties: false
      description: 'A quantile of samples.  Observe that the count is optional.  Some

        implementation may not maintain exact counts.

        '
      properties:
        count:
          description: The number of values below the threshold value.
          type: integer
        name:
          description: The name of the quantile.
          type: string
        percentage:
          description: The percentage of samples below the threshold value.
          format: float
          maximum: 100
          minimum: 0
          type: number
        threshold:
          description: The threshold of the quantile.
          format: float
          maximum: 1000
          minimum: 0
          type: number
      required:
      - name
      - threshold
      - percentage
      title: Quantile
      type: object
      x-examples:
        example:
          count: 2
          name: veryLow
          percentage: 0.0992
          threshold: 54
    SummaryPeriod:
      additionalProperties: false
      default: {}
      description: Summary diabetes statistics metadata
      properties:
        length:
          $id: '#/properties/period/properties/units'
          default: ''
          description: The length of the period.
          enum:
          - day
          - week
          examples:
          - week
          title: Period units
          type: string
        start:
          description: The start date of the period being reported.
          format: date-time
          type: string
        updated:
          description: The time that these statistics were last updated for the given
            period.
          format: date-time
          type: string
      required:
      - length
      - start
      - updated
      title: Summary statistics metadata
      type: object
      x-examples:
        example-1:
          length: week
          start: '2020-06-28T00:00:00Z'
          updated: '2020-07-05T00:10:00Z'
    SummaryReport:
      additionalProperties: false
      default: {}
      description: Summary diabetes statistics
      properties:
        period:
          $ref: '#/components/schemas/SummaryPeriod'
        stats:
          $ref: '#/components/schemas/SummaryStatistics'
      required:
      - period
      - stats
      title: Summary statistics
      type: object
      x-examples:
        example-1:
          period:
            length: week
            start: '2020-06-28T00:00:00Z'
            updated: '2020-07-05T00:10:00Z'
          stats:
            count: 2016
            mean: 107
            quantiles:
            - count: 2
              name: veryLow
              percentage: 0.0992
              threshold: 54
            - count: 202
              name: low
              percentage: 10.0198
              threshold: 80
            - count: 2011
              name: high
              percentage: 99.752
              threshold: 180
            - count: 2016
              name: veryHigh
              percentage: 100
              threshold: 250
            units: mg/dl
    SummaryRequest:
      additionalProperties: false
      default: {}
      description: "Request a set of named quantiles.  The named quantiles MUST include\
        \ the names: \"veryHigh\", \"high\", \"low\", \"veryLow\". Other named quantiles\
        \ MAY be provided. \n"
      properties:
        quantiles:
          items:
            additionalProperties: false
            properties:
              name:
                description: The name of the quantile.
                type: string
              threshold:
                description: The threshold value for the quantiles.  All samples must
                  be below the threshold to be included in the count.
                format: float
                type: number
            required:
            - name
            - threshold
            type: object
          type: array
        units:
          $ref: '#/components/schemas/SummaryRequest-properties-units'
      required:
      - units
      - quantiles
      title: Summary request
      type: object
    SummaryRequest-properties-units:
      enum:
      - mmol/L
      - mmol/l
      - mg/dL
      - mg/dl
      title: Blood Glucose Units
      type: string
      x-tags:
      - data
    SummaryResponse:
      additionalProperties: false
      default: {}
      description: 'A summary of the most recent diabetes data for a set of users. '
      properties:
        activity:
          $id: '#/properties/activity'
          additionalItems: false
          default: []
          description: A summary of which devices were used and when to upload diabetes
            data
          items:
            additionalProperties: false
            description: A report on when a diabetes device was most recently used
            properties:
              client:
                description: The client software that provided diabetes data
                properties:
                  name:
                    description: The name of the client software used to extract the
                      data
                    pattern: ^[a-zA-Z0-9](|[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])(\.[a-zA-Z0-9](|[a-zA-Z0-9-]{0,61}[a-zA-Z0-9]))+$
                    title: Client software name
                    type: string
                  platform:
                    description: The software platform on which the client software
                      was run
                    examples:
                    - macOS 10.15.4
                    title: Client software platform
                    type: string
                  private:
                    properties: {}
                    title: Metadata
                    type: object
                    x-tags:
                    - data
                  version:
                    description: The version of the client software used to extract
                      the data
                    pattern: ^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$
                    title: Client software version
                    type: string
                title: Diabetes client software package
                type: object
                x-examples:
                  example-1:
                    name: Tidepool Uploader
                    platform: macOS 10.15.4
                    version: 1.23.4
              device:
                additionalProperties: false
                default: {}
                description: The device used to provide diabetes data
                properties:
                  deviceManufacturers:
                    description: "An array of string tags indicating the manufacturer(s)\
                      \ of the device.\n\nIn order to avoid confusion resulting from\
                      \ referring to a single manufacturer with more than one name\u2014\
                      for example, using both 'Minimed' and 'Medtronic' interchangeably\u2014\
                      we restrict the set of strings used to refer to manufacturers\
                      \ to the set listed above and enforce *exact* string matches\
                      \ (including casing).\n\n`deviceManufacturers` is an array of\
                      \ one or more string \"tags\" because there are devices resulting\
                      \ from a collaboration between more than one manufacturer, such\
                      \ as the Tandem G4 insulin pump with CGM integration (a collaboration\
                      \ between `Tandem` and `Dexcom`)."
                    items:
                      type: string
                    type: array
                  deviceModel:
                    description: 'A string identifying the model of the device.


                      The `deviceModel` is a non-empty string that encodes the model
                      of device. We endeavor to match each manufacturer''s standard
                      for how they represent model name in terms of casing, whether
                      parts of the name are represented as one word or two, etc.'
                    type: string
                  deviceSerialNumber:
                    description: 'A string encoding the device''s serial number.


                      The `deviceSerialNumber` is a string that encodes the serial
                      number of the device. Note that even if a manufacturer only
                      uses digits in its serial numbers, the SN should be stored as
                      a string regardless.


                      Uniquely of string fields in the Tidepool device data models,
                      `deviceSerialNumber` *may* be an empty string. This is essentially
                      a compromise: having the device serial number is extremely important
                      (especially for e.g., clinical studies) but in 2016 we came
                      across our first case where we *cannot* recover the serial number
                      of the device that generated the data: Dexcom G5 data uploaded
                      to Tidepool through Apple iOS''s HealthKit integration.'
                    type: string
                  deviceTags:
                    description: 'An array of string tags indicating the function(s)
                      of the device.


                      The `deviceTags` array should be fairly self-explanatory as
                      an array of tags indicating the function(s) of a particular
                      device. For example, the Insulet OmniPod insulin delivery system
                      has the tags `bgm` and `insulin-pump` since the PDM is both
                      an insulin pump controller and includes a built-in blood glucose
                      monitor.'
                    items:
                      anyOf:
                      - enum:
                        - bgm
                        - cgm
                        - insulin-pump
                      type: string
                    type: array
                title: Upload Device
                type: object
              event:
                $ref: '#/components/schemas/UpdateEvent'
            title: Recent Upload Activity
            type: object
          title: Recent Upload Activity Summary
          type: array
        reports:
          description: Summary of recent glucose information.
          items:
            $ref: '#/components/schemas/SummaryReport'
          title: Recent Statisical Summaries
          type: array
        userid:
          $ref: '#/components/schemas/userId'
      required:
      - reports
      - userid
      title: Summary response
      type: object
      x-examples:
        example-1:
          activity:
          - client:
              name: Tidepool Uploader
              platform: macOS 10.15.4
              version: 1.23.4
            device:
              deviceManufacturers:
              - Bayer
              deviceName: Ascensia Contour Next One
              deviceSerialNumber: '123456'
            event:
              time: '2020-07-06T08:29:02Z'
              type: smbg
          reports:
          - period:
              length: week
              start: '2020-07-05T00:00:00Z'
              updated: 2020-07-011T08:29:02Z
            stats:
              count: 1860
              mean: 110
              quantiles:
              - count: 2
                name: veryLow
                percentage: 0.1075
                threshold: 54
              - count: 40
                name: low
                percentage: 2.1505
                threshold: 80
              - count: 1823
                name: high
                percentage: 90.4266
                threshold: 180
              - count: 1823
                name: veryHigh
                percentage: 90.4266
                threshold: 250
              units: mg/dl
          - period:
              length: week
              start: '2020-06-28T00:00:00Z'
              updated: '2020-07-05T00:10:00Z'
            stats:
              count: 2016
              mean: 107
              quantiles:
              - count: 2
                name: veryLow
                percentage: 0.0992
                threshold: 54
              - count: 202
                name: low
                percentage: 10.0198
                threshold: 80
              - count: 2011
                name: high
                percentage: 99.752
                threshold: 180
              - count: 2016
                name: veryHigh
                percentage: 100
                threshold: 250
              units: mg/dl
    SummaryStatistics:
      additionalProperties: false
      default: {}
      description: Summary diabetes statistics
      properties:
        count:
          description: Total number of samples in period.
          minimum: 0
          type: integer
        mean:
          description: Mean glucose over samples in period
          title: Mean glucose
          type: number
        quantiles:
          description: An array of quantile measurements.
          items:
            $ref: '#/components/schemas/Quantile'
          type: array
        units:
          $ref: '#/components/schemas/SummaryRequest-properties-units'
      title: Summary statistics
      type: object
      x-examples:
        example-1:
          count: 2016
          mean: 107
          quantiles:
          - count: 2
            name: veryLow
            percentage: 0.0992
            threshold: 54
          - count: 202
            name: low
            percentage: 10.0198
            threshold: 80
          - count: 2011
            name: high
            percentage: 99.752
            threshold: 180
          - count: 2016
            name: veryHigh
            percentage: 100
            threshold: 250
          units: mg/dl
    UpdateEvent:
      additionalProperties: false
      default: {}
      description: The time that that the device was last used to provide diabetes
        data
      properties:
        time:
          $id: '#/properties/time'
          default: ''
          description: The time of the most recent upload.
          examples:
          - '2020-06-20T14:20:02Z'
          format: date-time
          title: Last Upload Time
          type: string
        type:
          $id: '#/properties/type'
          default: ''
          description: The data type that was uploaded.
          enum:
          - smbg
          - cbg
          examples:
          - smbg
          title: Uploaded Data Type
          type: string
      required:
      - type
      - time
      title: Last Update Time
      type: object
      x-examples:
        example-1:
          time: '2020-07-06T08:29:02Z'
          type: smbg
    userId:
      description: String representation of a Tidepool User ID
      maxLength: 10
      minLength: 10
      pattern: ^[a-f0-9]{10}
      title: Tidepool User ID
      type: string
  securitySchemes:
    bearerToken:
      description: ''
      scheme: bearer
      type: http
    serverSecret:
      in: header
      name: x-tidepool-server-secret
      type: apiKey
    sessionToken:
      description: ''
      in: header
      name: x-tidepool-session-token
      type: apiKey
info:
  contact:
    email: support@tidepool.org
    name: API Support
    url: https://support.tidepool.org/
  description: Summary service
  license:
    name: BSD 2-Clause "Simplified" License
    url: https://github.com/tidepool-org/platform/blob/master/LICENSE
  termsOfService: https://developer.tidepool.org/terms-of-use/
  title: Summary
  version: '1.0'
openapi: 3.0.0
paths:
  /v1/clinics/{clinicid}/summaries:
    parameters:
    - in: path
      name: clinicid
      required: true
      schema:
        type: string
    post:
      description: Return summary information for all patients of a clinic
      operationId: get-v1-clinics-cliniid-summary
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SummaryRequest'
      responses:
        '200':
          content:
            application/json:
              examples: {}
              schema:
                items:
                  $ref: '#/components/schemas/SummaryResponse'
                type: array
          description: OK
      security:
      - sessionToken: []
      summary: Retrieve summaries for all patients of a clinic
      tags: []
  /v1/users/{userid}/summary:
    parameters:
    - in: path
      name: userid
      required: true
      schema:
        type: string
    post:
      description: Retrieve summary information
      operationId: post-v1-users-userid-summary
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SummaryRequest'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SummaryResponse'
          description: OK
      summary: ''
      tags: []
servers:
- description: localhost
  url: http://localhost:3000
- description: qa1
  url: https://qa1.development.tidepool.org
- description: qa2
  url: https://qa2.development.tidepool.org
- description: integration
  url: https://integration.external.tidepool.org
- description: production
  url: https://api.tidepool.org
tags:
- description: Tidepool Summary
  name: summary
