// Package Summary provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"github.com/getkin/kin-openapi/openapi3"
	"strings"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xa/W4buXZ/FYJdIHZ2JI2U2Bvrn9abbPcGm8Tp2m7RtVSYmjmSeJdDTkiObNUr4D7E",
	"fcL7JMUhOV/SSLGToGiBBYJY0pCH5+N3PocPNFFZriRIa+j4gZpkCRlzH18LDtLipxRMonluuZJ0TK+W",
	"QBL3jBg1t3dMA7FLZkmu1YqnkJKUsxlYMCRlltGI5lrloC0HR1eyDLqp4hOi5sR2nFAYSIlVBO6tZol1",
	"a0ryzFrQSOS/bljvv897v8W9s+nRH/WX3vQhjk6Hm8bj46PJpP+E5cfff0cjarkVQMdBNzV3TqaI2nWO",
	"T43VXC7oJqK5YHaudNYtb7W9XEaUJHdLniw7VXDHDNGFpBGFe5blAtV5QzOWXFySYdwfnvRf0ul+Hite",
	"uvjUfMWsM0u5/T1YFhQclqvZXyGxNKL3PcsW7nC3YLqJ6Aq0cYJ1yRkefp1pj+I/boa9s+lkkj4/nkz6",
	"B78f9Zpf/8D/gjF705u4d1Z+fu5g8Ni1x8+P//loMvm++ev3DkfNH3DVIayUqtoxw6be86b0oG1d5Sz5",
	"nS2g0yg1Kh5KhPSGtcfRK55CrpQg17lQLAVNmwDdAlLDpHTYH73ov6Qb5PANrHjigMLSlKORmfjY8O85",
	"EwYimsKcFQKjxybqQETqqFSWD5HjM4HDb3rPZDFniS00aLOLt3NJmNZsjWDziiUIVsJlyhNm3fclkKxB",
	"5cgcl9D0R/QnciLfSqJ0Chr5YyvFU5IoOS8ckDWYQjhac60yomEO2h+lCCOGy4VoH0HuuF2STPlQKYmS",
	"Pmb8429/nytNgrUiUuBeMlN2SZ6955JnkD4jTKbk2XtIrVaSJ88IlxZ0smRyAWwm1v/429/vAFmymgfv",
	"MWBr+U2lZscnfmiyZvCHcpPgxkJK2EytwJ0Lcq50AuQ53LPEPi9VmjGbLMGQIy4TUaT4U8KQ92Onu9sO",
	"U90SbghrWAd1oLRXSiA7oWirCSUzSFhhUFmggSDwPUWzrXpGEiUEmynNEABkBvYOQG6puilvREyRLAkz",
	"TugrJlPIyM8vCZemEFySvMhyb67XP793ul4E2kf7Drv1VG6dxm7fwH2istvjPo0ot5A5kO5E3PCD0wZ1",
	"PuI0plIQHaAuFcRTkJbP1xWMcX0HeNHHbhskvfKJVLIHWW7XlWtg3gaZqBRMm2AgRv4DCMgU2EoF5Nhk",
	"SYAly5ZSnxliLJMp0ylBQC/VHZJbEw25BoMhzFN2KZ5LYkFnBs/xsInI3RLQ2CRn2ppSIrcarV+RQXAa",
	"Z9M7pVPEj71TEQGb9LvympfiEjRn4kORzUAfUK7TQ6lZvxPlcpuJdLu3ldukHHS8T7MtOlsmIx+UDUUU",
	"rEASPiesHT+UFGv0Y0NSvuAW4xnBPy2qJnJELz8Qs1SFSMkMPUtpr7SKNQ0LplMBxjhxriX/VIBoRsw5",
	"B5G6M5yPlHkjRG0Mzt6cJupWxPOMrZ/j6UySJt765GrJDeoJDFqTMyHWzoezXKuMGxiTJVu1bbClOdx8",
	"bzVkyDLPcqUtk5Ycgckh8QRdSO0v+hGmT8kTJoixRcrBHJNZYVGuUTw8JXdAEoewRCtjiCo0mXNtLIIS",
	"EJFYdAF5njAplX1ONCRqhRH0sDm9IRcgQTMEbFnPjIkPDeTnE6/DwudhF5srJdulVsViSc7zXADhF5fP",
	"DPkLMGGXv3DbjEcHAH/lyrMvTI3zQia4ozstNsCPp9wGkjXg5oxrsSYGxLwH97lgklml1w6BDQYecTJz",
	"wYAnhWC68pR/baZL3PQW4zZYcpFJ/lGlVRxPQfAV6DUxa2MhI8sQ8d3Bt7NFGa7D+h7G/VvM3c6AQD6+",
	"eY9Yc7mYyXZ6SJS0WgkB2tHwSRDQxWYFF7bHJZkJpVKyEEWiDIZVya3SrZTA5PpiTsc3DxRkkWE1PVtg",
	"cZ64/5ts0elmGn0uhTSqR1/fkVCqbZeKm4j+7Nm6LLKM6fXXFHOBRF25GcssN5YnZqd+y0FzleKn7zTM",
	"6Zj+06BuPgeh8xwEih/94k1EkaJ55K7L+nRUiIZPBdeQonLD6SW9RqNUytBi/QnldS2XALmwSzqmdwC/",
	"+6O0pWM6ikdxLz7tjV5dxfHY/fuNRrTIUwwQ1YIfevEJLhj6BU3ZE1VgL45hK6IZMEnHw/iHiH4qmLTc",
	"t4L1qqgs+dEB3qk7NAXoBKTF3mEc9+Ozs1FE7VKDWSqR0vHJy03UOKWmIHZ2D+N+PDx71dr+Km5tHw6r",
	"/Uu+WG4RODvr/3DSPn64TeC0JcJfdokM47hFYXQSo5MUkqPCaLYYpAI7lk1E/y3o6BE4b9cFpXJdwPTG",
	"7xNyMTOgVyHKu34WucZYoXJPuk/IpcpgIjnuyZBlVy9mbE2ksiRjXFrGJXFFtd+PuXjHY4I+OmclVeJZ",
	"MVGAITMQvugilVb8o0aecNkDNCLrcVOYUgOduaZpji5C9fOGAg/zia0oQ4+ZC8XQ7TJ2zzOMjs7eGbZE",
	"+C2u2PF6cOGwBkMXN/VpHbIdPPfwwVthppwEVcy09NSIOhUqHxlrmlHgi/wbOW0H128Q96uo2gYuyD1W",
	"AOkqbIx7PcszIEdwn4jC8BUcN+1QLegCXhlmuw7wz0obe9DVXJaZNmVrGvko3ZVZQ9zunNnhoy0RXP53",
	"IvQfLUMV+zuximTL+GKgkZnIHRalghlLAgVX7aKsC46tgxf1sXxsgdfLXTMXOUNWCu/ImZVmn5Avv3GW",
	"bOD6V/hUgLFfA+xAArslP0RBT0urYGGI6wCqp15+TAtl6GyufX99eVVWh1VDa8ZkUmW1CY3IxCVJ/0mo",
	"O/8hePaE9smFa4x3aJ//J5bb5dC9TzryR12ZtH+vHagKLqUxdoAqi8yHC7ezIxBWSWULTOGQFoVpRzHa",
	"KGEeGtXxIft9yQuFg6ns0bnDZarK5SrW+4ScC1HluKwwFo3TleuswicBFGnZY7vI3pmJnphuujS8PWsK",
	"RdLhivraLdo+z29tGi0qUdYRHXTwxw6eKo81uZLmqwbK58SE84KpM2UsNusgbXuk7AxX+W5hQJs+2fEa",
	"lli+4tb1Rd/x1CmoXjGoHkcNjt963G4zezM9yKx/11OONl1od7NabCrvliARLH5IsDMarxzloA3d3vOS",
	"4UaL+KvXTugUyxWk7Ah3MRM62V3/uKzFCSovm14uPZjDrOJRHG91prsc+w7PzXT8Ig6mg120Lf9sr3lt",
	"QL9Nd0DesHApdkWxE+UBw0/KgjXKsHGr3rV+q3c15Sho74uTG/ojW4Om03LlB3/yuUlAGs7IayWtKjT5",
	"APeWXEgUr2ucSoejFy9PTvFEWAUhXLHRyNenV/Gr8ehsHI9+a0TfbIYVyLSBrZvHN9NlFXCoTBgOG+d2",
	"dNPDV6dx1U0P4y/upofxDyf7u+mX8YFmetQfnsQn+3vp4avRi4O9dNx/OTo9PdBMtyjsaaa7qOxpqKM/",
	"5x3/l+cd02Y53JiG/S+N+PYNLJRtzcrLOok3+5VDpWWJgW3C74HJKt+4ynyHdONNfHM17ZggtCrR/bPz",
	"aiyUATOFdgMe8+gMV/X937Ywc/qJqvrMG6Ip0jcceP7pnF84jIzodWnhchKRZUoM3iH88YPAD4tB+i78",
	"FU2z/eheKYQKiVwHS7d7mc7LOdcu7v5UZuevubjRnEyE8Wd46XXHTJhLPOlShy8VOgvtMLKoOKJ0L0cd",
	"hb+vm/tbt6WqzBRfDV+OR7ErDab7hiVB8e9QrFAqX+2Z5/gfuuXAR5+Vw/UnuNRrFtVZvh/sNyZXrmqK",
	"aDJbINtN0dyT6fZbIEjJG6R85Zk4PP8JnDrxpzvyo2q25H9MtHhKMejA2upZnjqz15Arbf1FOpCENeBX",
	"47SBE/9afXeCWVfkh2JxuCPZqrYPrQ+v5Jq18uH+rXbczWe7t642O3Q4u11beRUg3KvwLyjcS9e69TCg",
	"yds3fhr+LpR6Qz8Nb35t37+cx72z6cMw3jQcqIPkLhANJIXmdn2JwnsjzIBp0Ffqd5DV5VTc5X+vqSyt",
	"zV35CHoF+hISDU63HJlaQuifQgy/79nATs+v7xm/oc7HOf8F1p6gwb6q4uDzBN36nnUbdgiimNgV+yQq",
	"LUscm5AxLlAZRY7g/ZeSXF/pRX3M+ce35NKvwESvRRDcjAeDsLPf3Dmge0s5lNu/GhYcuz1odJ4/Xr4h",
	"o95r4e5fTeglz3LB5xzSCSXvwurt4xfcLotZP1HZoFIFclB2rIOZULNBxowFPXj39vVPHy5/ckETdGYu",
	"5peBnZpgCisQ6I5tidz6npr3CgMDulPQbDXCMR6hcpAs53RMX/TjfuzvlC4dugar4cBfEDGDB/+Bp5uB",
	"qcYK4weaM80ysL5jDvZHArVZyo20GUqtLiAKl6k7rn9hcZAr01Ep/wq20LKaETVGKH52JQTJmcWgY7y3",
	"+uOpE9TfC0F3px+Vsf8+fO2lc394WmspzOV+VOm6hGJZG+S5cFcylBz81aja7dgj38CXI3j/6rUcjThd",
	"juL4Sac9qpzeniPu3ovY8YKLX1rxxhm27eg37sKFKa9HoFU0hxWQChuHrYHkEV1uwjh48KOjElnrx+Eq",
	"zJu+Faqa/LdwtQc6GKnNtePh/xtungSXPfDYbKp04i1UB7zxYCBUwsRSGTt+EcfxTjlXPabYR7RD5Sc2",
	"7Ifohn1jfyvWtwl9YsNOEqOnkBh1kGheI4N7zN5MHKbT2NFBj+X88PZcq7RI/G6sLH2LUiUdU0FsqzAu",
	"C4dqIDzd/E8AAAD//z+4XcGzMgAA",
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file.
func GetSwagger() (*openapi3.Swagger, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	swagger, err := openapi3.NewSwaggerLoader().LoadSwaggerFromData(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("error loading Swagger: %s", err)
	}
	return swagger, nil
}

